### ISSUE TITLE
Which 100 samples did you use for each dataset?

### ISSUE THREAD

**Issue by Qinyu-Allen-Zhao** [pliang279/HEMM#33]
Hi!

Thank you for your great work! I'm wondering where to find the list of 100 sample you used for each dataset. The whole datasets are too big for us to run. 

Best regards,
Qinyu

**Comment by akshayg08** [comment]
We used the top 100 samples from each evaluation set.

**Comment by Qinyu-Allen-Zhao** [comment]
Thank you!!! I see!
